# Generated by Django 5.0 on 2023-12-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
    ]
